Repository dendense/himitsu, pull requests merged in 2020-09, with the labels that each got.

#15 Merge dendense-branch to testing-branch
  src/components/Footer.js
  src/components/Icon.js
  src/components/IconText.js
  src/components/Nav.js
  src/fragments/twopart/LeftPart.js
  src/fragments/twopart/RightPart.js
  src/pages/index.js
  src/styles/_footerComponent.scss
  src/styles/_icontextComponent.scss
  src/styles/_navComponent.scss
  src/styles/_postComponent.scss
  src/styles/index.scss
Labels: enhancement

#16 Merge pillamore-branch to testing-branch
  gatsby-node.js
  src/components/Footer.js
  src/components/Hero.js
  src/components/Icon.js
  src/components/IconText.js
  src/components/Nav.js
  src/fragments/twopart/LeftPart.js
  src/fragments/twopart/RightPart.js
  src/pages/index.js
  src/styles/_footerComponent.scss
  src/styles/_icontextComponent.scss
  src/styles/_navComponent.scss
  src/styles/_postComponent.scss
  src/styles/index.scss
  src/templates/indexTemplate.js
Labels: enhancement

#18 Testing branch
  gatsby-config.js
Labels: bug, enhancement

#19 Minor Updates (Again)
  content/blog/20200826-aimyonconcert/index.md
  src/images/himitsu-logo.png
Labels: bug

#22 Updating Testing Branch
  content/blog/20200903-hinabingoep28/images.jpg
  content/blog/20200903-hinabingoep28/index.md
  gatsby-node.js
  package-lock.json
  package.json
  src/components/Sidebar.js
  src/templates/blogTemplate.js
  src/templates/groupTemplate.js
  src/templates/tagsTemplate.js
Labels: bug, enhancement

#24 Dendense branch
  src/templates/blogTemplate.js
Labels: enhancement, good first issue

#28 Adding More Post & Fixing Layout Style
  content/blog/20200903-harunoisheanybody/image.jpg
  content/blog/20200903-harunoisheanybody/index.md
  content/blog/20200903-kojikoji127/image.jpg
  content/blog/20200903-kojikoji127/index.md
  gatsby-node.js
  src/components/Sidebar.js
  src/fragments/PostGrid.js
  src/templates/indexTemplate.js
  src/templates/postTemplate.js
  src/templates/tagsTemplate.js
Labels: enhancement, good first issue

#29 Adding More Post & Fixing Layout Style
  content/blog/20200903-harunoisheanybody/image.jpg
  content/blog/20200903-harunoisheanybody/index.md
  content/blog/20200903-kojikoji127/image.jpg
  content/blog/20200903-kojikoji127/index.md
  gatsby-node.js
  src/components/Sidebar.js
  src/fragments/PostGrid.js
  src/templates/indexTemplate.js
  src/templates/postTemplate.js
  src/templates/tagsTemplate.js
Labels: bug, enhancement

#30 Merge pillamore-branch to testing-branch
  gatsby-node.js
  src/pages/index.js
  src/templates/pageTemplate.js
Labels: bug

#31 Merge testing-branch to master
  gatsby-node.js
  src/pages/index.js
  src/templates/pageTemplate.js
Labels: bug

#32 Major Update
  gatsby-node.js
  src/fragments/PostGrid.js
  src/pages/index.js
  src/styles/_postComponent.scss
  src/templates/groupTemplate.js
  src/templates/pageTemplate.js
  src/templates/tagsTemplate.js
Labels: enhancement, good first issue

#33 Adding More Posts
  content/blog/20200827-sheissummer-single/index.md
  content/blog/20200903-harunoisheanybody/index.md
  content/blog/20200903-kojikoji127/index.md
  content/blog/20200904-sheissummer-hairsalon/featured.png
  content/blog/20200904-sheissummer-hairsalon/index.md
Labels: duplicate, enhancement, good first issue

#34 Adding more posts
  content/blog/20200827-sheissummer-single/index.md
  content/blog/20200903-harunoisheanybody/index.md
  content/blog/20200903-kojikoji127/index.md
  content/blog/20200904-sheissummer-hairsalon/featured.png
  content/blog/20200904-sheissummer-hairsalon/index.md
Labels: duplicate, enhancement, good first issue

#35 Merge pillamore-branch to testing-branch
  src/components/Footer.js
  src/components/Layout.js
Labels: bug

#36 Merge pillamore-branch to testing-branch
  src/components/Footer.js
  src/templates/groupTemplate.js
Labels: bug

#37 Merge pillamore-branch to testing-branch
  gatsby-node.js
  src/components/Nav.js
  src/templates/searchTemplate.js
Labels: enhancement

#38 Modified Search Page
  src/templates/searchTemplate.js
Labels: enhancement

#39 Update Essentials Feature
  content/blog/20200903-kojikoji127/index.md
  content/blog/20200904-sheissummer-hairsalon/index.md
  gatsby-config.js
  package-lock.json
  package.json
  src/components/Footer.js
  src/components/PostList.js
  src/components/Sidebar.js
  src/images/notfound.png
  src/pages/404.js
  src/pages/news.js
  src/pages/test.js
  src/styles/_404.scss
  src/templates/groupTemplate.js
  src/utils/utilityFunction.js
Labels: enhancement, good first issue

#40 Beta Development (Ready to Publish)
  content/blog/20200903-kojikoji127/index.md
  content/blog/20200904-sheissummer-hairsalon/index.md
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  src/components/Footer.js
  src/components/Layout.js
  src/components/Nav.js
  src/components/PostList.js
  src/components/Sidebar.js
  src/images/notfound.png
  src/pages/404.js
  src/pages/news.js
  src/pages/test.js
  src/styles/_404.scss
  src/styles/_footerComponent.scss
  src/styles/_groupTemplate.scss
  src/styles/index.scss
  src/templates/groupTemplate.js
  src/templates/searchTemplate.js
  src/utils/utilityFunction.js
Labels: enhancement, good first issue

#41 Fixing Minor Style (Grid Style)
  src/components/PostList.js
  src/fragments/twoPartStyle.js
  src/pages/48groups.js
  src/pages/underground.js
  src/styles/_postComponent.scss
  src/templates/groupTemplate.js
  src/templates/postTemplate.js
Labels: enhancement, good first issue

#42 Sync Branch
  README.md
  content/blog/20200908-hinatazaka46-sonnakotonaiyo/image.jpg
  content/blog/20200908-hinatazaka46-sonnakotonaiyo/index.md
  src/templates/groupTemplate.js
  src/templates/tagsTemplate.js
Labels: enhancement

#43 Adding New Post, News Banner, Fixing Duplicate Posts
  content/blog/20200910-taskhavefun-kiminandakara/image.jpg
  content/blog/20200910-taskhavefun-kiminandakara/index.md
  package-lock.json
  package.json
  src/assets/himitsu-news2.png
  src/components/Footer.js
  src/components/Hero.js
  src/templates/groupTemplate.js
Labels: enhancement, good first issue

#48 Fix Disquss Comment
  gatsby-config.js
  src/templates/postTemplate.js
Labels: enhancement

#49 Testing branch (Fixing Disquss Comment)
  gatsby-config.js
  src/templates/postTemplate.js
Labels: enhancement

#57 Testing branch
  content/blog/20191212-nogizaka46album/index.md
  content/blog/20191212-nogizaka46album/n46-live.jpg
  content/blog/20200825-keyakizaka46/index.md
  content/blog/20200825-keyakizaka46/keyakite.jpg
  content/blog/20200825-nogizaka46/index.md
  content/blog/20200825-nogizaka46/n46-live.jpg
  content/blog/20200826-aimyonconcert/aimyon-concert.jpg
  content/blog/20200826-aimyonconcert/index.md
  content/blog/20200827-hinatazaka46-doremisolasido/H462A.jpg
  content/blog/20200827-hinatazaka46-doremisolasido/index.md
  content/blog/20200827-hinatazaka46single/index.md
  content/blog/20200903-harunoisheanybody/index.md
  content/blog/20200903-hinabingoep28/images.jpg
  content/blog/20200903-hinabingoep28/index.md
  content/blog/20200903-kojikoji127/index.md
  gatsby-config.js
  package-lock.json
  package.json
  src/styles/_postComponent.scss
  src/templates/postTemplate.js
Labels: enhancement

#60 Updated Index Page
  src/components/Nav.js
  src/fragments/twoPartStyle.js
  src/pages/concert.js
  src/pages/index.js
  src/pages/variety.js
Labels: enhancement

#61 Adding More Post
  content/blog/20200919-nogizaka46-isee-pv/image.jpg
  content/blog/20200919-nogizaka46-isee-pv/index.md
Labels: enhancement
